// Central module registry. Drives sidebar visibility, /modules install page, and route guards.

export type ModuleCategory =
  | "Core" | "Sales" | "Purchases" | "Inventory" | "POS" | "Restaurant"
  | "Finance" | "HR & Payroll" | "CRM" | "Projects & Service" | "Reports"
  | "School ERP" | "Hotel ERP" | "NGO" | "Mining" | "Help & Learning" | "Administration" | "Platform";

export type ModuleRoute = { title: string; url: string; iconName?: string; superAdminOnly?: boolean };
export type ModuleDef = { key: string; label: string; category: ModuleCategory; description: string; routes: ModuleRoute[]; defaultInstalled: boolean; core?: boolean };

export const MODULES: ModuleDef[] = [
  { key: "core_home", label: "Dashboard", category: "Core", core: true, defaultInstalled: true, description: "Home dashboard & summary widgets.", routes: [{ title: "Summary", url: "/dashboard", iconName: "Home" }] },
  { key: "sales", label: "Sales & Invoicing", category: "Sales", defaultInstalled: true, description: "Customers, quotes, invoices, credit notes and receipts.", routes: [{ title: "Customers", url: "/customers", iconName: "Users" }, { title: "Quotes", url: "/quotes", iconName: "FileText" }, { title: "Sales Invoices", url: "/invoices", iconName: "ReceiptText" }, { title: "Credit Notes", url: "/credit-notes", iconName: "Undo2" }, { title: "Receive Payments", url: "/receipts", iconName: "CreditCard" }] },
  { key: "purchases", label: "Purchases & Bills", category: "Purchases", defaultInstalled: true, description: "Suppliers, purchase orders, quotation comparison, bills, payments and expenses.", routes: [{ title: "Suppliers", url: "/suppliers", iconName: "Truck" }, { title: "Purchase Orders", url: "/purchase-orders", iconName: "ShoppingCart" }, { title: "Quotation Comparison", url: "/quotation-comparison", iconName: "FileSearch" }, { title: "Bills", url: "/bills", iconName: "FileBox" }, { title: "Supplier Payments", url: "/bill-payments", iconName: "Wallet" }, { title: "Expenses", url: "/expenses", iconName: "Receipt" }, { title: "Expense Categories", url: "/expense-rules", iconName: "Tags" }] },
  { key: "finance", label: "Finance & GL", category: "Finance", core: true, defaultInstalled: true, description: "Banking, chart of accounts, journals and cashbook.", routes: [{ title: "Banking", url: "/banking", iconName: "Landmark" }, { title: "Bank Accounts", url: "/bank-accounts", iconName: "Landmark" }, { title: "Bank Rules", url: "/bank-rules", iconName: "Sparkles" }, { title: "Reconciliation", url: "/reconciliation", iconName: "Scale" }, { title: "Recon Sessions", url: "/reconciliation-sessions", iconName: "Scale" }, { title: "Chart of Accounts", url: "/chart-of-accounts", iconName: "BookOpen" }, { title: "Journal Entries", url: "/journal-entries", iconName: "BookText" }, { title: "Smart Posting Wizard", url: "/posting-wizard", iconName: "Sparkles" }, { title: "Cashbook", url: "/cashbook", iconName: "BookText" }, { title: "Opening Balances", url: "/opening-balances", iconName: "Sparkles" }, { title: "Period Close", url: "/period-close", iconName: "CalendarClock" }] },
  { key: "fixed_assets", label: "Fixed Assets", category: "Finance", defaultInstalled: true, description: "Asset register and monthly depreciation.", routes: [{ title: "Fixed Assets", url: "/fixed-assets", iconName: "Landmark" }] },
  { key: "budgets", label: "Budgets", category: "Finance", defaultInstalled: true, description: "Budget vs. actuals.", routes: [{ title: "Budgets", url: "/budgets", iconName: "PiggyBank" }] },
  { key: "multi_currency", label: "Multi-Currency", category: "Finance", core: true, defaultInstalled: true, description: "Core FX rates and multi-currency posting. ZMW is the default base currency.", routes: [{ title: "Exchange Rates", url: "/fx-rates", iconName: "Coins" }] },
  { key: "inventory", label: "Inventory", category: "Inventory", defaultInstalled: true, description: "Stock items, locations, movements, transfers, counts and audit controls.", routes: [{ title: "Inventory Dashboard", url: "/inventory", iconName: "LayoutDashboard" }, { title: "Control Center", url: "/inventory-control-centre", iconName: "Gauge" }, { title: "Items", url: "/stock", iconName: "Boxes" }, { title: "Locations", url: "/inventory/locations", iconName: "Warehouse" }, { title: "Production Batches", url: "/inventory/production", iconName: "Factory" }, { title: "Stock Transfers", url: "/inventory/transfers", iconName: "ArrowLeftRight" }, { title: "Stock Card", url: "/inventory/stock-card", iconName: "ScrollText" }, { title: "Reconciliation", url: "/inventory/reconciliation", iconName: "Scale" }, { title: "Inventory → GL Reconciliation", url: "/inventory/gl-reconciliation", iconName: "Scale" }, { title: "Cashier Records", url: "/inventory/cashier-records", iconName: "NotebookPen" }, { title: "Warehouses", url: "/warehouses", iconName: "Warehouse" }, { title: "Stock Adjustments", url: "/stock-adjustments", iconName: "ClipboardEdit" }, { title: "Stock Takes", url: "/stock-counts", iconName: "ClipboardList" }, { title: "Batches & Expiry", url: "/stock-batches", iconName: "Layers" }, { title: "Serial Numbers", url: "/stock-serials", iconName: "Barcode" }, { title: "Inventory Sheets", url: "/inventory-sheets", iconName: "ClipboardList" }] },
  { key: "hr_payroll", label: "HR & Payroll", category: "HR & Payroll", defaultInstalled: true, description: "Employees, attendance, leave, payroll, jobs and recruitment.", routes: [{ title: "Payroll Dashboard", url: "/payroll-dashboard", iconName: "LayoutDashboard" }, { title: "Employees", url: "/employees", iconName: "UserSquare" }, { title: "Jobs & Recruitment", url: "/jobs", iconName: "BriefcaseBusiness" }, { title: "Attendance", url: "/attendance", iconName: "CalendarCheck" }, { title: "Leave", url: "/leave", iconName: "CalendarDays" }, { title: "Timesheet", url: "/timesheet", iconName: "Clock" }, { title: "Payroll", url: "/payroll", iconName: "Banknote" }, { title: "Payroll Setup", url: "/payroll-setup", iconName: "Settings2" }, { title: "Payroll Transactions", url: "/payroll-transactions", iconName: "Wallet2" }, { title: "Payroll Tools", url: "/payroll-tools", iconName: "Calculator" }, { title: "Payroll Schedules", url: "/reports/payroll-schedules", iconName: "Banknote" }] },
  { key: "school_erp", label: "School Management", category: "School ERP", defaultInstalled: false, description: "Modern school ERP for admissions, learners, academics, fees, attendance, examinations, communication, transport and finance.", routes: [{ title: "School Dashboard", url: "/school", iconName: "School" }, { title: "Admissions & Enrolment", url: "/school/admissions", iconName: "UserPlus" }, { title: "Students", url: "/school/students", iconName: "GraduationCap" }, { title: "Parents & Guardians", url: "/school/parents", iconName: "Users" }, { title: "Classes & Subjects", url: "/school/academics", iconName: "BookOpen" }, { title: "Timetable", url: "/school/timetable", iconName: "CalendarDays" }, { title: "Attendance", url: "/school/attendance", iconName: "CalendarCheck" }, { title: "Examinations & Results", url: "/school/exams", iconName: "ClipboardCheck" }, { title: "Report Cards", url: "/school/report-cards", iconName: "FileText" }, { title: "Fees & Billing", url: "/school/fees", iconName: "ReceiptText" }, { title: "Fee Collections", url: "/school/payments", iconName: "CreditCard" }, { title: "Scholarships & Discounts", url: "/school/scholarships", iconName: "BadgePercent" }, { title: "Hostel & Boarding", url: "/school/boarding", iconName: "BedDouble" }, { title: "Transport", url: "/school/transport", iconName: "Bus" }, { title: "Staff & HR", url: "/school/staff", iconName: "UsersRound" }, { title: "Parent Portal", url: "/school/parent-portal", iconName: "Smartphone" }, { title: "Student Portal", url: "/school/student-portal", iconName: "Laptop" }, { title: "School Reports", url: "/school/reports", iconName: "BarChart3" }] },
  { key: "hotel_erp", label: "Hotel Management", category: "Hotel ERP", defaultInstalled: false, description: "Full hospitality ERP covering reservations, front desk, rooms, housekeeping, restaurant POS, guests, events, billing, inventory and hotel accounting.", routes: [{ title: "Hotel Dashboard", url: "/hotel", iconName: "Hotel" }, { title: "Reservations", url: "/hotel/reservations", iconName: "CalendarCheck" }, { title: "Front Desk", url: "/hotel/front-desk", iconName: "ConciergeBell" }, { title: "Room Rack", url: "/hotel/room-rack", iconName: "BedDouble" }, { title: "Guests & Profiles", url: "/hotel/guests", iconName: "Users" }, { title: "Rooms & Room Types", url: "/hotel/rooms", iconName: "DoorOpen" }, { title: "Housekeeping", url: "/hotel/housekeeping", iconName: "Sparkles" }, { title: "Maintenance", url: "/hotel/maintenance", iconName: "Wrench" }, { title: "Check-in / Check-out", url: "/hotel/check-in-out", iconName: "LogIn" }, { title: "Hotel POS", url: "/hotel/pos", iconName: "ShoppingBag" }, { title: "Restaurant & Bar", url: "/hotel/restaurant", iconName: "UtensilsCrossed" }, { title: "Banquets & Events", url: "/hotel/events", iconName: "CalendarRange" }, { title: "Invoices & Folios", url: "/hotel/folios", iconName: "ReceiptText" }, { title: "Payments & Deposits", url: "/hotel/payments", iconName: "CreditCard" }, { title: "Night Audit", url: "/hotel/night-audit", iconName: "MoonStar" }, { title: "Inventory & Purchasing", url: "/hotel/inventory", iconName: "Boxes" }, { title: "Hotel Accounting", url: "/hotel/accounting", iconName: "Landmark" }, { title: "Hotel Reports", url: "/hotel/reports", iconName: "BarChart3" }, { title: "Guest Portal", url: "/hotel/guest-portal", iconName: "Smartphone" }] },
  { key: "public_services", label: "Public Services", category: "Platform", defaultInstalled: true, description: "Secure public-facing forms, links, job applications, quotation requests and customer services.", routes: [{ title: "Public Services", url: "/public-services", iconName: "Globe2" }] },
  { key: "reports", label: "Reports & Statements", category: "Reports", core: true, defaultInstalled: true, description: "Financial statements, statutory returns and operational analytics.", routes: [{ title: "Reports", url: "/reports", iconName: "BarChart3" }, { title: "Inventory Flow & Audit", url: "/reports/inventory-flow-audit", iconName: "FileBarChart" }, { title: "Trial Balance", url: "/reports/trial-balance", iconName: "BookText" }, { title: "Customer Statement", url: "/reports/customer-statement", iconName: "Users" }, { title: "Supplier Statement", url: "/reports/supplier-statement", iconName: "Truck" }, { title: "Annual Financial Statements", url: "/reports/afs", iconName: "Sparkles" }, { title: "VAT Return (VAT 3)", url: "/reports/vat-return", iconName: "Receipt" }, { title: "Income Tax Computation", url: "/reports/income-tax", iconName: "Receipt" }, { title: "Turnover Tax", url: "/reports/turnover-tax", iconName: "Receipt" }] },
  { key: "compliance", label: "Compliance & Statutory", category: "Reports", defaultInstalled: true, description: "ZRA, NAPSA, NHIMA and other statutory obligations.", routes: [{ title: "Compliance", url: "/compliance", iconName: "ShieldCheck" }] },
  { key: "retail_pos", label: "Retail POS", category: "POS", defaultInstalled: true, description: "Fast touchscreen shop till with stock and GL posting.", routes: [{ title: "SifoPOS Hub", url: "/sifopos", iconName: "LayoutGrid" }, { title: "Retail POS", url: "/pos", iconName: "ShoppingBag" }, { title: "POS Sales History", url: "/pos-sales", iconName: "Receipt" }, { title: "Retail Command Center", url: "/pos/retail-command-center", iconName: "Gauge" }, { title: "Worker Command Center", url: "/pos/command-center", iconName: "LayoutGrid" }, { title: "Worker Terminal (POS shell)", url: "/w", iconName: "Monitor" }, { title: "Worker Access & Roles", url: "/pos-workers", iconName: "ShieldCheck" }] },
  { key: "learning", label: "Help & Learning", category: "Help & Learning", core: true, defaultInstalled: true, description: "Accounting basics, Dr/Cr rules and Zambian compliance guides.", routes: [{ title: "Learn Centre", url: "/learn", iconName: "GraduationCap" }, { title: "New Company Setup", url: "/learn/new-company", iconName: "ClipboardList" }, { title: "Accounting Basics", url: "/learn/accounting-basics", iconName: "GraduationCap" }] },
  { key: "admin", label: "Administration", category: "Administration", defaultInstalled: true, description: "Company setup, users, roles, approvals and audit controls.", routes: [{ title: "Administration", url: "/admin", iconName: "Settings" }, { title: "Company Setup", url: "/setup", iconName: "Building2" }, { title: "Users & Roles", url: "/roles", iconName: "ShieldCheck" }, { title: "Audit Logs", url: "/audit-logs", iconName: "History" }] },
];