import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle2, CircleAlert, RefreshCw, Save, Search } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { SifoWorkspaceShell } from "@/components/sifo/SifoWorkspaceShell";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/zra-item-mapping")({component:ZraItemMapping});
function ZraItemMapping(){const [items,setItems]=useState<any[]>([]);const [q,setQ]=useState("");const [saving,setSaving]=useState<string|null>(null);
 const load=async()=>{const {data}=await supabase.from("stock_items").select("id,name,sku,zra_item_code,zra_item_class_code,zra_vat_category_code,zra_sync_status").order("name");setItems(data??[])};useEffect(()=>{void load()},[]);
 const save=async(id:string,patch:any)=>{setSaving(id);await supabase.from("stock_items").update({...patch,zra_sync_status:patch.zra_item_class_code?"mapped":undefined}).eq("id",id);await load();setSaving(null)};
 const filtered=items.filter(i=>String(i.name+" "+(i.sku||"")).toLowerCase().includes(q.toLowerCase()));const unmapped=items.filter(i=>!i.zra_item_class_code).length;
 return <SifoWorkspaceShell title="ZRA Item Mapping" purpose="Map inventory items to the ZRA classification and tax fields already supported by SifoBooks. Mapping is not a claim of ZRA certification." icon={CircleAlert} breadcrumbs={[{label:"Home",to:"/dashboard"},{label:"Business Control Centre",to:"/business-control-centre" as any},{label:"ZRA Item Mapping"}]} actions={<Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}>
 <div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><div className="text-xs text-muted-foreground">Items</div><div className="text-2xl font-bold">{items.length}</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Need classification</div><div className="text-2xl font-bold text-amber-700">{unmapped}</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Mapped</div><div className="text-2xl font-bold text-emerald-700">{items.length-unmapped}</div></Card></div>
 <Card className="p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item or SKU…"/></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-2">Item</th><th className="p-2">ZRA item code</th><th className="p-2">UNSPSC / class</th><th className="p-2">VAT category</th><th className="p-2">Status</th><th/></tr></thead><tbody>{filtered.map(i=><tr key={i.id} className="border-b"><td className="p-2"><b>{i.name}</b><div className="text-xs text-muted-foreground">{i.sku||"No SKU"}</div></td><td className="p-2"><Input defaultValue={i.zra_item_code||""} onBlur={e=>{if(e.target.value!==i.zra_item_code)void save(i.id,{zra_item_code:e.target.value})}}/></td><td className="p-2"><Input defaultValue={i.zra_item_class_code||""} onBlur={e=>{if(e.target.value!==i.zra_item_class_code)void save(i.id,{zra_item_class_code:e.target.value})}}/></td><td className="p-2"><Input defaultValue={i.zra_vat_category_code||""} onBlur={e=>{if(e.target.value!==i.zra_vat_category_code)void save(i.id,{zra_vat_category_code:e.target.value})}}/></td><td className="p-2">{["mapped","registered","synced"].includes(String(i.zra_sync_status||"").toLowerCase())?<Badge><CheckCircle2 className="mr-1 h-3 w-3"/>Mapped</Badge>:<Badge variant="outline">Needs review</Badge>}</td><td className="p-2">{saving===i.id&&<Save className="h-4 w-4 animate-pulse"/>}</td></tr>)}</tbody></table></div></Card>
 </SifoWorkspaceShell>}