import { Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { BarChart3, Beef, Boxes, FileText, PackageCheck, Printer, RefreshCw, Scissors, Scale, ShoppingCart, Tags, WalletCards } from "lucide-react";
import { calculateYield, weightedCostPerKg } from "@/lib/butchery";
import { printHtmlDocument } from "@/services/printDocument";

export type ButcherySection = "dashboard"|"products"|"receiving"|"processing"|"scale"|"labels"|"prices"|"inventory"|"sales"|"reports"|"invoice";
type Item={id:string;name:string;sku:string|null;category:string|null;sell_price:number;cost_price:number;quantity_on_hand:number};
type BP={id:string;item_id:string;animal_type:string;cut_name:string|null;price_per_kg:number;scale_enabled:boolean;label_enabled:boolean};

const nav:[ButcherySection,string,any][]=[
 ["dashboard","Dashboard",BarChart3],["products","Products & Cuts",Beef],["receiving","Receiving",PackageCheck],
 ["processing","Processing & Yield",Scissors],["scale","Weighing Scale",Scale],["labels","Labels",Tags],
 ["prices","Price Lists",WalletCards],["inventory","Inventory",Boxes],["sales","Sales",ShoppingCart],
 ["reports","Reports",BarChart3],["invoice","Invoice / ZRA",FileText]
];

export function ButcherySuite({section}:{section:ButcherySection}){
 const [items,setItems]=useState<Item[]>([]),[bp,setBp]=useState<BP[]>([]),[sales,setSales]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const [selected,setSelected]=useState(""),[animal,setAnimal]=useState("beef"),[cut,setCut]=useState(""),[price,setPrice]=useState("");
 const [input,setInput]=useState("250"),[saleable,setSaleable]=useState("230"),[waste,setWaste]=useState("20"),[cost,setCost]=useState("15000"),[weight,setWeight]=useState("1.200");
 const load=async()=>{setLoading(true);const [a,b,c]=await Promise.all([
  supabase.from("stock_items").select("id,name,sku,category,sell_price,cost_price,quantity_on_hand").order("name").limit(2000),
  supabase.from("butchery_products").select("id,item_id,animal_type,cut_name,price_per_kg,scale_enabled,label_enabled").eq("is_active",true),
  supabase.from("pos_sales").select("id,sale_no,sold_at,total,tax,discount,status").order("sold_at",{ascending:false}).limit(100)
 ]);if(a.error)toast.error(a.error.message);if(b.error)toast.error(b.error.message);if(c.error)toast.error(c.error.message);setItems((a.data||[]) as Item[]);setBp((b.data||[]) as BP[]);setSales(c.data||[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const map=useMemo(()=>new Map(bp.map(x=>[x.item_id,x])),[bp]),meat=useMemo(()=>items.filter(x=>map.has(x.id)),[items,map]),chosen=items.find(x=>x.id===selected);
 const y=calculateYield(+input,+saleable,+waste),costKg=weightedCostPerKg(+cost,+saleable);
 const saveCut=async()=>{if(!chosen||!cut||!price)return toast.error("Select item, cut and price/kg");const{data:u}=await supabase.auth.getUser();if(!u.user)return;const{error}=await supabase.from("butchery_products").upsert({user_id:u.user.id,item_id:chosen.id,animal_type:animal,cut_name:cut,price_per_kg:+price,min_price_per_kg:0,scale_enabled:true,label_enabled:true,is_active:true} as any,{onConflict:"user_id,item_id"});if(error)toast.error(error.message);else{toast.success("Butchery cut saved");setCut("");setPrice("");await load()}};
 const postBatch=async()=>{if(!selected)return toast.error("Select source stock item");if(y.balanceKg<-.001)return toast.error("Output plus waste exceeds input");const out=meat.find(x=>x.id!==selected);if(!out)return toast.error("Add an output cut first");const{error}=await supabase.rpc("post_butchery_processing",{_source_item_id:selected,_input_qty:+input,_input_unit:"kg",_input_cost:+cost,_waste_qty:+waste,_reference:"BUT-"+Date.now(),_outputs:[{item_id:out.id,qty:+saleable,unit:"kg",note:out.name}]} as any);if(error)toast.error(error.message);else{toast.success("Processing batch posted");await load()}};
 const printLabel=()=>{if(!chosen)return toast.error("Select a cut");const kg=+weight,p=+(map.get(chosen.id)?.price_per_kg||chosen.sell_price||0);const html="<div style='font-family:Arial;width:80mm;border:1px solid #111;padding:14px'><h2>"+chosen.name+"</h2><p>SifoBooks Butchery</p><p>Weight: <b>"+kg.toFixed(3)+" kg</b></p><p>Price/kg: <b>K"+p.toFixed(2)+"</b></p><h1>K"+(kg*p).toFixed(2)+"</h1><p>SKU: "+(chosen.sku||"N/A")+"</p><p>Keep refrigerated</p></div>";void printHtmlDocument("SifoBooks Meat Label",html,"butchery-label-"+(chosen.sku||chosen.id)+".pdf")};
 const title=(nav.find(x=>x[0]===section)||nav[0])[1];
 return <div className="min-h-[calc(100dvh-2rem)] bg-[#f4f7f6] text-[#173b3a] -mx-2 -mt-2">
  <header className="sticky top-0 z-30 border-b border-[#164744] bg-[#073b38] text-white shadow-lg"><div className="flex flex-wrap items-center gap-3 px-4 py-3">
   <Link to="/retail/butchery" className="flex items-center gap-2"><span className="rounded-xl bg-[#e5b83f] p-2 text-[#073b38]"><Beef className="h-5 w-5"/></span><span><b>SifoBooks</b><small className="block text-[9px] tracking-widest text-emerald-200">BUTCHERY 2026</small></span></Link>
   <Badge className="bg-emerald-400 text-emerald-950">Online</Badge><Badge className="bg-white/10 text-white">Main Branch</Badge><Button asChild size="sm" className="ml-auto bg-[#e5b83f] text-[#173b3a]"><Link to="/retail/butchery-pos"><ShoppingCart className="mr-1 h-4 w-4"/>Open POS</Link></Button><Button variant="ghost" size="icon" className="text-white" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/></Button>
  </div><nav className="flex gap-1 overflow-x-auto border-t border-white/10 px-3 py-2">{nav.map(([k,l,I])=><Link key={k} to={("/retail/butchery-"+k) as any} className={"flex shrink-0 items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-bold "+(section===k?"bg-[#e5b83f] text-[#173b3a]":"text-white/75 hover:bg-white/10")}><I className="h-3.5 w-3.5"/>{l}</Link>)}</nav></header>
  <main className="mx-auto max-w-[1600px] space-y-5 p-4 lg:p-6"><div><div className="text-xs font-black uppercase tracking-widest text-emerald-700">Butchery Operations</div><h1 className="text-2xl font-black md:text-3xl">{title}</h1><p className="text-sm text-slate-500">Uses the existing SifoBooks inventory, POS, accounting and compliance engine.</p></div>
   {section==="dashboard"&&<Dashboard meat={meat} sales={sales} y={y}/>}
   {section==="products"&&<Products items={items} meat={meat} map={map} selected={selected} setSelected={setSelected} animal={animal} setAnimal={setAnimal} cut={cut} setCut={setCut} price={price} setPrice={setPrice} saveCut={saveCut}/>}
   {section==="receiving"&&<Links title="Receive Meat Stock" links={[["/inventory/receive-stock","Receive Stock"],["/inventory/opening-stock","Opening Stock"],["/suppliers","Suppliers"],["/warehouses","Warehouses / Locations"]]}/>}
   {section==="processing"&&<Processing meat={meat} selected={selected} setSelected={setSelected} input={input} setInput={setInput} saleable={saleable} setSaleable={setSaleable} waste={waste} setWaste={setWaste} cost={cost} setCost={setCost} y={y} costKg={costKg} postBatch={postBatch}/>}
   {section==="scale"&&<Links title="Weighing Scale" links={[["/retail/butchery-pos","Use Scale in POS"],["/printing-settings","Hardware / Printing"],["/network-setup","LAN / Devices"]]}/>}
   {section==="labels"&&<Labels meat={meat} selected={selected} setSelected={setSelected} weight={weight} setWeight={setWeight} printLabel={printLabel}/>}
   {section==="prices"&&<Prices meat={meat} map={map}/>}
   {section==="inventory"&&<Inventory meat={meat}/>}
   {section==="sales"&&<Sales sales={sales}/>}
   {section==="reports"&&<Reports meat={meat} sales={sales}/>}
   {section==="invoice"&&<Links title="Invoice & ZRA" links={[["/zra-smart-invoice","ZRA Smart Invoice"],["/pos-sales","POS Sales / Reprint"],["/receipts","Receipts"],["/printing-settings","Printing Settings"]]}/>}
   {loading&&<div className="fixed bottom-4 right-4 rounded-full bg-[#073b38] px-4 py-2 text-xs font-bold text-white">Refreshing data…</div>}
  </main></div>
}

function Dashboard({meat,sales,y}:any){const today=sales.filter((x:any)=>String(x.sold_at).slice(0,10)===new Date().toISOString().slice(0,10)).reduce((s:number,x:any)=>s+Number(x.total||0),0);return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Sales today","K"+today.toFixed(2)],["Weight stock",meat.reduce((s:number,x:any)=>s+Number(x.quantity_on_hand||0),0).toFixed(2)+" kg"],["Butchery cuts",String(meat.length)],["Yield",y.saleablePercent.toFixed(1)+"%"]].map(([a,b])=><Card key={a}><CardContent className="p-5"><div className="text-xs text-slate-500">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Quick actions</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-4"><Button asChild><Link to="/retail/butchery-pos">Open POS</Link></Button><Button asChild variant="outline"><Link to="/inventory/receive-stock">Receive Stock</Link></Button><Button asChild variant="outline"><Link to="/retail/butchery-processing">Process Meat</Link></Button><Button asChild variant="outline"><Link to="/printing-settings">Printing</Link></Button></CardContent></Card></>}

function Products({items,meat,map,selected,setSelected,animal,setAnimal,cut,setCut,price,setPrice,saveCut}:any){return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>Products & Cuts</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-white px-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Existing stock item</option>{items.filter((x:any)=>!map.has(x.id)).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="h-10 w-full rounded-md border bg-white px-3" value={animal} onChange={e=>setAnimal(e.target.value)}>{["beef","mutton","pork","chicken","processed","offal"].map(x=><option key={x}>{x}</option>)}</select><Input value={cut} onChange={e=>setCut(e.target.value)} placeholder="Cut name"/><Input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price/kg"/><Button className="w-full" onClick={saveCut}>Save Butchery Cut</Button></CardContent></Card><Card><CardHeader><CardTitle>Active cuts</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{meat.map((x:any)=>{const m=map.get(x.id);return <tr key={x.id} className="border-b"><td className="py-3 font-semibold">{x.name}</td><td>{m?.animal_type}</td><td>{m?.cut_name||"—"}</td><td className="text-right">K{Number(m?.price_per_kg||x.sell_price||0).toFixed(2)}/kg</td><td className="text-right">{Number(x.quantity_on_hand||0).toFixed(3)} kg</td></tr>})}</tbody></table></div></CardContent></Card></div>}

function Processing({meat,selected,setSelected,input,setInput,saleable,setSaleable,waste,setWaste,cost,setCost,y,costKg,postBatch}:any){return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>Meat Processing & Yield</CardTitle></CardHeader><CardContent className="space-y-4"><select className="h-10 w-full rounded-md border bg-white px-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Source carcass / primal</option>{meat.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-4">{[["Input kg",input,setInput],["Saleable kg",saleable,setSaleable],["Waste/trim kg",waste,setWaste],["Input cost",cost,setCost]].map(([l,v,s]:any)=><div><label className="text-xs font-semibold">{l}</label><Input type="number" value={v} onChange={e=>s(e.target.value)}/></div>)}</div><div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><small>Saleable yield</small><b className="block text-2xl">{y.saleablePercent.toFixed(1)}%</b></CardContent></Card><Card><CardContent className="p-4"><small>Waste</small><b className="block text-2xl">{y.wastePercent.toFixed(1)}%</b></CardContent></Card><Card><CardContent className="p-4"><small>Cost / saleable kg</small><b className="block text-2xl">K{costKg.toFixed(2)}</b></CardContent></Card></div><Button disabled={!selected||y.balanceKg<-.001} onClick={postBatch}>Post Processing Batch</Button></CardContent></Card><Card><CardHeader><CardTitle>Yield control</CardTitle></CardHeader><CardContent><div className="text-4xl font-black">{y.balanceKg.toFixed(3)} kg</div><p className="text-sm text-slate-500">Unexplained balance. Input must equal saleable output + waste/trim.</p><Badge variant={Math.abs(y.balanceKg)<.001?"default":"destructive"}>{Math.abs(y.balanceKg)<.001?"Balanced":"Review variance"}</Badge></CardContent></Card></div>}

function Labels({meat,selected,setSelected,weight,setWeight,printLabel}:any){return <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Barcode / Meat Labels</CardTitle></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-white px-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select cut</option>{meat.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Input type="number" step=".001" value={weight} onChange={e=>setWeight(e.target.value)}/><Button onClick={printLabel}><Printer className="mr-2 h-4 w-4"/>Print Label</Button></CardContent></Card><Card><CardHeader><CardTitle>Label contents</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2">{["Product name","Weight","Price/kg","Total price","SKU / barcode","Packed date","Keep refrigerated","SifoBooks branding"].map(x=><div key={x} className="rounded-xl border p-3 text-sm">✓ {x}</div>)}</CardContent></Card></div>}

function Prices({meat,map}:any){const [saving,setSaving]=useState<string|null>(null);const [values,setValues]=useState<Record<string,string>>({});const save=async(x:any)=>{const v=Number(values[x.id]??map.get(x.id)?.price_per_kg??x.sell_price??0);if(!Number.isFinite(v)||v<0)return toast.error("Enter a valid price");setSaving(x.id);const{error}=await supabase.from("stock_items").update({sell_price:v} as any).eq("id",x.id);const m=map.get(x.id);let metaError:any=null;if(m) { const r=await supabase.from("butchery_products").update({price_per_kg:v} as any).eq("id",m.id); metaError=r.error; } setSaving(null);if(error||metaError)toast.error((error||metaError).message);else toast.success(x.name+" price updated")};return <Card><CardHeader><CardTitle>Price Lists</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="py-2 text-left">Cut</th><th>Animal</th><th className="text-right">Current</th><th className="text-right">New price/kg</th><th/></tr></thead><tbody>{meat.map((x:any)=>{const m=map.get(x.id),v=values[x.id]??String(Number(m?.price_per_kg||x.sell_price||0));return <tr key={x.id} className="border-b"><td className="py-3 font-semibold">{x.name}</td><td>{m?.animal_type}</td><td className="text-right">K{Number(m?.price_per_kg||x.sell_price||0).toFixed(2)}</td><td><Input className="ml-auto w-28" type="number" value={v} onChange={e=>setValues(z=>({...z,[x.id]:e.target.value}))}/></td><td className="text-right"><Button size="sm" onClick={()=>void save(x)} disabled={saving===x.id}>{saving===x.id?"Saving":"Save"}</Button></td></tr>})}</tbody></table></div></CardContent></Card>}

function Inventory({meat}:any){return <><Links title="Inventory Controls" links={[["/inventory","Inventory"],["/inventory/stock-card","Stock Card"],["/inventory/transfers","Transfers"],["/inventory/opening-stock","Opening Stock"],["/inventory/receive-stock","Receive Stock"]]}/><Card><CardHeader><CardTitle>Butchery Stock Levels</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{meat.map((x:any)=><div key={x.id} className="rounded-xl border bg-white p-4"><b>{x.name}</b><div className="mt-1 text-2xl font-black">{Number(x.quantity_on_hand||0).toFixed(3)} kg</div><small>K{(Number(x.quantity_on_hand||0)*Number(x.cost_price||0)).toFixed(2)} cost</small></div>)}</div></CardContent></Card></>}

function Sales({sales}:any){return <><Links title="Sales Controls" links={[["/retail/butchery-pos","Butchery POS"],["/pos-sales","POS Sales History"],["/receipts","Receipts"],["/retail-control-center","Retail Control Center"]]}/><Card><CardHeader><CardTitle>Recent Sales</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{sales.slice(0,25).map((x:any)=><tr key={x.id} className="border-b"><td className="py-3">{x.sale_no||x.id.slice(0,8)}</td><td>{new Date(x.sold_at).toLocaleString()}</td><td><Badge>{x.status}</Badge></td><td className="text-right font-bold">K{Number(x.total||0).toFixed(2)}</td></tr>)}</tbody></table></div></CardContent></Card></>}

function Reports({sales,meat}:any){const valid=sales.filter((x:any)=>!["void","voided"].includes(x.status));const total=valid.reduce((s:number,x:any)=>s+Number(x.total||0),0),vat=valid.reduce((s:number,x:any)=>s+Number(x.tax||0),0);return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Gross sales","K"+total.toFixed(2)],["VAT","K"+vat.toFixed(2)],["Transactions",String(valid.length)],["Stock value","K"+meat.reduce((s:number,x:any)=>s+Number(x.quantity_on_hand||0)*Number(x.cost_price||0),0).toFixed(2)]].map(([a,b])=><Card key={a}><CardContent className="p-5"><small>{a}</small><b className="mt-2 block text-2xl">{b}</b></CardContent></Card>)}</div><Links title="Report Centre" links={[["/reports","All Reports"],["/reports/pos-integrity","POS Integrity"],["/reports/inventory-valuation","Inventory Valuation"],["/reports/vat","VAT"],["/reports/sales-by-item","Sales by Item"]]}/></>}

function Links({title,links}:{title:string;links:string[][]}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{links.map(([to,label])=><Button key={to} asChild variant="outline" className="justify-start"><Link to={to as any}>{label}</Link></Button>)}</CardContent></Card>}