import type { DemoIndustry } from "./types";

/** SAMPLE DATA ONLY — see src/lib/demo/types.ts for the safety contract. */
export const payrollDemo: DemoIndustry = {
  slug: "payroll",
  name: "Payroll",
  product: "SifoPayroll",
  tagline: "Employees, gross-to-net, payslips and Zambian statutory returns — on its own or with the books.",
  description:
    "Walk a full monthly pay cycle: the employee register, the pay run, the review checks that catch problems before approval, branded payslips, the payment batch and the PAYE, NAPSA and NHIMA returns that follow.",
  highlights: ["86 sample employees", "Gross-to-net workings", "PAYE, NAPSA & NHIMA returns", "Payslips & payment batch"],
  accent: {
    gradient: "from-indigo-500/15 via-sky-500/10 to-background",
    text: "text-indigo-600 dark:text-indigo-400",
    ring: "ring-indigo-500/30",
  },
  sections: [
    {
      slug: "dashboard",
      name: "Dashboard",
      group: "Overview",
      blurb: "Where this month's payroll stands and what is still outstanding.",
      iconName: "LayoutDashboard",
      kpis: [
        { label: "Period", value: "March 2026", hint: "Open" },
        { label: "Employees on the run", value: "86" },
        { label: "Gross pay", value: "K 1,482,600" },
        { label: "Total deductions", value: "K 431,940", tone: "info" },
        { label: "Net pay", value: "K 1,050,660", tone: "good" },
        { label: "Employer cost", value: "K 1,571,556", hint: "Incl. NAPSA & NHIMA employer share" },
      ],
      actions: [
        { label: "Run payroll", variant: "primary", section: "run-payroll" },
        { label: "Review & approve", variant: "secondary", section: "review" },
      ],
      blocks: [
        {
          kind: "flow",
          title: "Payroll cycle",
          steps: [
            { label: "Draft", detail: "Employees loaded", state: "Done", tone: "good" },
            { label: "Calculated", detail: "Gross-to-net run", state: "Done", tone: "good" },
            { label: "Reviewed", detail: "4 exceptions open", state: "In progress", tone: "warn" },
            { label: "Approved", detail: "Awaiting finance director", state: "Waiting", tone: "neutral" },
            { label: "Paid", detail: "Bank batch not sent", state: "Waiting", tone: "neutral" },
            { label: "Filed", detail: "PAYE, NAPSA, NHIMA", state: "Waiting", tone: "neutral" },
          ],
        },
        {
          kind: "panel",
          title: "Needs attention",
          items: [
            { label: "Employees without a NAPSA number", value: "2", tone: "bad" },
            { label: "Employees without bank details", value: "1", tone: "warn" },
            { label: "Overtime above 40 hours", value: "3", tone: "warn" },
            { label: "Net pay variance over 25% vs last month", value: "2", tone: "warn" },
          ],
        },
        {
          kind: "chart",
          variant: "bars",
          title: "Net pay by month",
          unit: "K",
          series: [
            { label: "Nov", value: 998400 },
            { label: "Dec", value: 1184300 },
            { label: "Jan", value: 1012700 },
            { label: "Feb", value: 1029500 },
            { label: "Mar", value: 1050660, tone: "good" },
          ],
        },
      ],
    },
    {
      slug: "employees",
      name: "Employees",
      group: "People",
      blurb: "The employee register with pay, statutory and bank details.",
      iconName: "UserSquare",
      kpis: [
        { label: "Active employees", value: "86" },
        { label: "Departments", value: "7" },
        { label: "Joined this month", value: "3", tone: "good" },
        { label: "Missing statutory IDs", value: "2", tone: "bad" },
      ],
      actions: [
        { label: "New employee", variant: "secondary" },
        { label: "Open pay run", variant: "ghost", section: "run-payroll" },
      ],
      blocks: [
        {
          kind: "table",
          title: "Employee register",
          note: "Search first — creating a new employee is the secondary action.",
          columns: ["Employee no", "Name", "Department", "Grade", "Basic pay", "NAPSA no", "Status"],
          numericColumns: [4],
          statusColumn: 6,
          rows: [
            ["EMP-0012", "Chileshe Mumba", "Finance", "G5", "K 21,400", "123456789", "Active"],
            ["EMP-0027", "Naomi Zulu", "Operations", "G4", "K 16,800", "234567890", "Active"],
            ["EMP-0034", "Peter Nkandu", "Warehouse", "G2", "K 7,950", "—", "Missing ID"],
            ["EMP-0041", "Bwalya Chanda", "Sales", "G3", "K 11,200", "345678901", "Active"],
            ["EMP-0058", "Grace Lungu", "HR", "G4", "K 15,300", "456789012", "Active"],
            ["EMP-0063", "Isaac Phiri", "Workshop", "G2", "K 8,400", "—", "Missing ID"],
            ["EMP-0071", "Mutale Sinkala", "Finance", "G3", "K 12,600", "567890123", "On leave"],
          ],
        },
      ],
    },
    {
      slug: "periods",
      name: "Payroll periods",
      group: "Payroll",
      blurb: "Monthly periods with draft, approval, posting and lock status.",
      iconName: "CalendarDays",
      blocks: [
        {
          kind: "table",
          title: "Periods",
          columns: ["Period", "Pay date", "Employees", "Gross", "Net", "Status"],
          numericColumns: [2, 3, 4],
          statusColumn: 5,
          rows: [
            ["March 2026", "28 Mar 2026", 86, "K 1,482,600", "K 1,050,660", "Open"],
            ["February 2026", "27 Feb 2026", 84, "K 1,451,200", "K 1,029,500", "Closed"],
            ["January 2026", "30 Jan 2026", 84, "K 1,428,900", "K 1,012,700", "Closed"],
            ["December 2025", "20 Dec 2025", 83, "K 1,662,400", "K 1,184,300", "Locked"],
          ],
        },
        {
          kind: "notes",
          title: "Controls in this demo",
          lines: [
            "A closed period can only be reopened with a reason, and the reopen is written to the audit trail.",
            "A locked period cannot be edited at all — corrections go through the next open period.",
          ],
        },
      ],
    },
    {
      slug: "run-payroll",
      name: "Run payroll",
      group: "Payroll",
      blurb: "Gross-to-net for the open period, line by line.",
      iconName: "Calculator",
      kpis: [
        { label: "Basic pay", value: "K 1,192,300" },
        { label: "Allowances", value: "K 214,800" },
        { label: "Overtime", value: "K 75,500" },
        { label: "PAYE", value: "K 268,420" },
        { label: "NAPSA (employee)", value: "K 71,180" },
        { label: "NHIMA (employee)", value: "K 14,826" },
      ],
      actions: [
        { label: "Calculate pay run", variant: "primary" },
        { label: "Send for review", variant: "secondary", section: "review" },
      ],
      blocks: [
        {
          kind: "table",
          title: "Gross to net — March 2026",
          columns: ["Employee", "Basic", "Allowances", "Overtime", "Gross", "PAYE", "NAPSA", "NHIMA", "Loans", "Net pay"],
          numericColumns: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          rows: [
            ["Chileshe Mumba", "K 21,400", "K 3,200", "K 0", "K 24,600", "K 6,148", "K 1,230", "K 246", "K 0", "K 16,976"],
            ["Naomi Zulu", "K 16,800", "K 2,400", "K 1,150", "K 20,350", "K 4,562", "K 1,018", "K 204", "K 800", "K 13,766"],
            ["Peter Nkandu", "K 7,950", "K 900", "K 640", "K 9,490", "K 1,048", "K 475", "K 95", "K 0", "K 7,872"],
            ["Bwalya Chanda", "K 11,200", "K 1,800", "K 0", "K 13,000", "K 2,205", "K 650", "K 130", "K 450", "K 9,565"],
            ["Grace Lungu", "K 15,300", "K 2,100", "K 0", "K 17,400", "K 3,678", "K 870", "K 174", "K 0", "K 12,678"],
          ],
        },
        {
          kind: "notes",
          title: "How the figures are produced",
          lines: [
            "PAYE, NAPSA and NHIMA rates are held as dated rules, so a rate change applies from its effective month only.",
            "NAPSA is capped at the current statutory monthly maximum contribution held in the rules table.",
            "Illustrative figures — confirm current rates with ZRA, NAPSA and NHIMA for a live run.",
          ],
        },
      ],
    },
    {
      slug: "review",
      name: "Review & approve",
      group: "Payroll",
      blurb: "Exceptions and variances checked before anyone is paid.",
      iconName: "CheckCheck",
      kpis: [
        { label: "Payslips checked", value: "82 / 86" },
        { label: "Exceptions", value: "4", tone: "warn" },
        { label: "Variance vs February", value: "+2.1%" },
        { label: "Blocking issues", value: "2", tone: "bad" },
      ],
      actions: [
        { label: "Approve pay run", variant: "primary", section: "payments" },
        { label: "Send back to draft", variant: "ghost", section: "run-payroll" },
      ],
      blocks: [
        {
          kind: "table",
          title: "Validation results",
          columns: ["Check", "Employee", "Detail", "Severity"],
          statusColumn: 3,
          rows: [
            ["Missing NAPSA number", "Peter Nkandu", "Cannot appear on the NAPSA return", "Blocking"],
            ["Missing NAPSA number", "Isaac Phiri", "Cannot appear on the NAPSA return", "Blocking"],
            ["Overtime outlier", "Naomi Zulu", "58 hours vs 12-hour average", "Warning"],
            ["Net pay variance", "Bwalya Chanda", "-31% vs February (loan started)", "Warning"],
          ],
        },
        {
          kind: "notes",
          title: "Separation of duties",
          lines: [
            "Whoever prepared the run cannot approve it — the approval records who approved, when and why.",
            "The run is read-only from review onward until it is sent back to draft.",
          ],
        },
      ],
    },
    {
      slug: "payslips",
      name: "Payslips",
      group: "Payroll",
      blurb: "Branded payslips, downloadable and password-protected.",
      iconName: "FileText",
      actions: [{ label: "Download all payslips", variant: "primary" }],
      blocks: [
        {
          kind: "panel",
          title: "Payslip — Naomi Zulu · March 2026",
          items: [
            { label: "Basic pay", value: "K 16,800.00" },
            { label: "Housing allowance", value: "K 2,400.00" },
            { label: "Overtime (9.5 hrs)", value: "K 1,150.00" },
            { label: "Gross pay", value: "K 20,350.00", tone: "info" },
            { label: "PAYE", value: "-K 4,562.00" },
            { label: "NAPSA (employee 5%)", value: "-K 1,017.50" },
            { label: "NHIMA (employee 1%)", value: "-K 203.50" },
            { label: "Staff loan repayment", value: "-K 800.00" },
            { label: "Net pay", value: "K 13,767.00", tone: "good" },
            { label: "Paid to", value: "ZANACO ****4182" },
          ],
        },
        {
          kind: "table",
          title: "Payslip register",
          columns: ["Employee", "Period", "Net pay", "Delivery", "Status"],
          numericColumns: [2],
          statusColumn: 4,
          rows: [
            ["Chileshe Mumba", "Mar 2026", "K 16,976", "Email (protected PDF)", "Ready"],
            ["Naomi Zulu", "Mar 2026", "K 13,767", "Email (protected PDF)", "Ready"],
            ["Peter Nkandu", "Mar 2026", "K 7,872", "Printed", "Ready"],
            ["Bwalya Chanda", "Mar 2026", "K 9,565", "Email (protected PDF)", "Ready"],
          ],
        },
      ],
    },
    {
      slug: "payments",
      name: "Payments",
      group: "Payroll",
      blurb: "The payment batch prepared from the approved run.",
      iconName: "Wallet2",
      kpis: [
        { label: "Batch total", value: "K 1,050,660" },
        { label: "Bank transfers", value: "78" },
        { label: "Mobile money", value: "7" },
        { label: "Cash", value: "1", tone: "warn" },
      ],
      actions: [{ label: "Generate bank file", variant: "primary" }],
      blocks: [
        {
          kind: "table",
          title: "Payment batch PB-2026-03",
          columns: ["Method", "Account", "Employees", "Amount", "Status"],
          numericColumns: [2, 3],
          statusColumn: 4,
          rows: [
            ["Bank transfer", "ZANACO Current ****2210", 78, "K 981,420", "Prepared"],
            ["Mobile money", "Airtel Money merchant", 7, "K 62,340", "Prepared"],
            ["Cash", "Head office petty cash", 1, "K 6,900", "Needs approval"],
          ],
        },
        {
          kind: "notes",
          title: "Reconciliation",
          lines: [
            "Batch total must equal the approved net pay before a bank file can be produced.",
            "Once the bank statement is imported, the batch is matched line by line.",
          ],
        },
      ],
    },
    {
      slug: "statutory",
      name: "Statutory",
      group: "Compliance",
      blurb: "PAYE, NAPSA and NHIMA returns prepared and reconciled.",
      iconName: "ShieldCheck",
      kpis: [
        { label: "PAYE due", value: "K 268,420" },
        { label: "NAPSA total", value: "K 142,360", hint: "Employee + employer" },
        { label: "NHIMA total", value: "K 29,652" },
        { label: "Filing deadline", value: "10 Apr 2026", tone: "warn" },
      ],
      actions: [{ label: "Prepare returns", variant: "primary" }],
      blocks: [
        {
          kind: "table",
          title: "Returns for March 2026",
          columns: ["Return", "Employees", "Employee share", "Employer share", "Total", "Status"],
          numericColumns: [1, 2, 3, 4],
          statusColumn: 5,
          rows: [
            ["ZRA PAYE schedule", 86, "K 268,420", "—", "K 268,420", "Ready to file"],
            ["NAPSA return", 84, "K 71,180", "K 71,180", "K 142,360", "2 employees missing IDs"],
            ["NHIMA return", 86, "K 14,826", "K 14,826", "K 29,652", "Ready to file"],
          ],
        },
        {
          kind: "notes",
          title: "How submission works",
          lines: [
            "SifoBooks prepares and validates the return files and tracks their submission status and responses.",
            "Direct transmission depends on your own certified ZRA and NAPSA credentials — SifoBooks does not claim certification on your behalf.",
          ],
        },
      ],
    },
    {
      slug: "attendance-leave",
      name: "Attendance & leave",
      group: "People",
      blurb: "The inputs behind overtime, absence and leave pay.",
      iconName: "CalendarCheck",
      blocks: [
        {
          kind: "board",
          title: "Leave requests",
          columns: [
            { label: "Requested", cards: [{ title: "Grace Lungu", meta: "Annual · 5 days", badge: "Apr" }, { title: "Isaac Phiri", meta: "Sick · 2 days", badge: "Mar" }] },
            { label: "Approved", tone: "good", cards: [{ title: "Mutale Sinkala", meta: "Annual · 10 days", badge: "Mar" }] },
            { label: "Declined", tone: "bad", cards: [{ title: "Peter Nkandu", meta: "Unpaid · 7 days", badge: "Mar" }] },
          ],
        },
        {
          kind: "table",
          title: "Overtime captured this period",
          columns: ["Employee", "Hours", "Rate", "Amount", "Source"],
          numericColumns: [1, 3],
          rows: [
            ["Naomi Zulu", "9.5", "1.5x", "K 1,150", "Timesheet"],
            ["Peter Nkandu", "6.0", "1.5x", "K 640", "Attendance clock"],
            ["Isaac Phiri", "12.0", "2.0x", "K 1,290", "Timesheet"],
          ],
        },
      ],
    },
    {
      slug: "reports",
      name: "Reports",
      group: "Reporting",
      blurb: "Register, employer cost, statutory liabilities and variance.",
      iconName: "BarChart3",
      blocks: [
        {
          kind: "grid",
          title: "Payroll report pack",
          cells: [
            { label: "Payroll register", sub: "Every employee, gross to net" },
            { label: "Gross-to-net summary", sub: "Totals by component" },
            { label: "Employer cost", sub: "NAPSA, NHIMA, WCF, SDL" },
            { label: "Statutory liabilities", sub: "What is owed and when" },
            { label: "Payroll by department", sub: "Cost centre and branch splits" },
            { label: "Payroll variance", sub: "This month vs last" },
            { label: "Overtime report", sub: "Hours and cost by employee" },
            { label: "Payment schedule", sub: "Bank and mobile money batch" },
            { label: "Year to date", sub: "Per employee YTD figures" },
          ],
        },
        {
          kind: "chart",
          variant: "donut",
          title: "Where the gross pay goes",
          series: [
            { label: "Net pay", value: 1050660, tone: "good" },
            { label: "PAYE", value: 268420 },
            { label: "NAPSA", value: 71180 },
            { label: "NHIMA", value: 14826 },
            { label: "Loans & other", value: 77514 },
          ],
        },
      ],
    },
    {
      slug: "settings",
      name: "Settings",
      group: "Setup",
      blurb: "Pay components, grades and statutory rules.",
      iconName: "Settings2",
      blocks: [
        {
          kind: "table",
          title: "Pay components",
          columns: ["Component", "Type", "Basis", "Taxable", "Status"],
          statusColumn: 4,
          rows: [
            ["Basic salary", "Earning", "Fixed", "Yes", "Active"],
            ["Housing allowance", "Earning", "15% of basic", "Yes", "Active"],
            ["Transport allowance", "Earning", "Fixed", "Yes", "Active"],
            ["Overtime", "Earning", "Hourly x multiplier", "Yes", "Active"],
            ["PAYE", "Statutory", "Dated tax bands", "—", "Active"],
            ["NAPSA", "Statutory", "5% employee + 5% employer, capped", "—", "Active"],
            ["NHIMA", "Statutory", "1% employee + 1% employer", "—", "Active"],
            ["Staff loan", "Deduction", "Instalment", "No", "Active"],
          ],
        },
        {
          kind: "notes",
          title: "Rates are dated, not hard-coded",
          lines: [
            "Every statutory rate carries an effective date, so historical payslips keep the rate that applied then.",
            "Confirm current rates against ZRA, NAPSA and NHIMA guidance before running live payroll.",
          ],
        },
      ],
    },
  ],
};
