/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedStockAdjustmentsRouteImport } from './routes/_authenticated/stock-adjustments'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedJournalEntriesRouteImport } from './routes/_authenticated/journal-entries'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCreditNotesRouteImport } from './routes/_authenticated/credit-notes'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedChartOfAccountsRouteImport } from './routes/_authenticated/chart-of-accounts'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedBillPaymentsRouteImport } from './routes/_authenticated/bill-payments'
import { Route as AuthenticatedBankingRouteImport } from './routes/_authenticated/banking'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReportsTrialBalanceRouteImport } from './routes/_authenticated/reports.trial-balance'
import { Route as AuthenticatedReportsPnlRouteImport } from './routes/_authenticated/reports.pnl'
import { Route as AuthenticatedReportsBalanceSheetRouteImport } from './routes/_authenticated/reports.balance-sheet'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes.new'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockAdjustmentsRoute =
  AuthenticatedStockAdjustmentsRouteImport.update({
    id: '/stock-adjustments',
    path: '/stock-adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalEntriesRoute =
  AuthenticatedJournalEntriesRouteImport.update({
    id: '/journal-entries',
    path: '/journal-entries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditNotesRoute =
  AuthenticatedCreditNotesRouteImport.update({
    id: '/credit-notes',
    path: '/credit-notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartOfAccountsRoute =
  AuthenticatedChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillPaymentsRoute =
  AuthenticatedBillPaymentsRouteImport.update({
    id: '/bill-payments',
    path: '/bill-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankingRoute = AuthenticatedBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsTrialBalanceRoute =
  AuthenticatedReportsTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsPnlRoute = AuthenticatedReportsPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedReportsRoute,
} as any)
const AuthenticatedReportsBalanceSheetRoute =
  AuthenticatedReportsBalanceSheetRouteImport.update({
    id: '/balance-sheet',
    path: '/balance-sheet',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedQuotesRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/bill-payments': typeof AuthenticatedBillPaymentsRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/credit-notes': typeof AuthenticatedCreditNotesRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/reports/pnl': typeof AuthenticatedReportsPnlRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/bill-payments': typeof AuthenticatedBillPaymentsRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/credit-notes': typeof AuthenticatedCreditNotesRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/reports/pnl': typeof AuthenticatedReportsPnlRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/banking': typeof AuthenticatedBankingRoute
  '/_authenticated/bill-payments': typeof AuthenticatedBillPaymentsRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/credit-notes': typeof AuthenticatedCreditNotesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/_authenticated/reports/pnl': typeof AuthenticatedReportsPnlRoute
  '/_authenticated/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/attendance'
    | '/audit-logs'
    | '/banking'
    | '/bill-payments'
    | '/bills'
    | '/budgets'
    | '/chart-of-accounts'
    | '/compliance'
    | '/credit-notes'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/invoices'
    | '/journal-entries'
    | '/leave'
    | '/notifications'
    | '/onboarding'
    | '/payroll'
    | '/purchase-orders'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/setup'
    | '/stock'
    | '/stock-adjustments'
    | '/subscription'
    | '/super-admin'
    | '/suppliers'
    | '/warehouses'
    | '/customers/$id'
    | '/invoices/new'
    | '/quotes/new'
    | '/reports/balance-sheet'
    | '/reports/pnl'
    | '/reports/trial-balance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/attendance'
    | '/audit-logs'
    | '/banking'
    | '/bill-payments'
    | '/bills'
    | '/budgets'
    | '/chart-of-accounts'
    | '/compliance'
    | '/credit-notes'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/invoices'
    | '/journal-entries'
    | '/leave'
    | '/notifications'
    | '/onboarding'
    | '/payroll'
    | '/purchase-orders'
    | '/quotes'
    | '/receipts'
    | '/reports'
    | '/setup'
    | '/stock'
    | '/stock-adjustments'
    | '/subscription'
    | '/super-admin'
    | '/suppliers'
    | '/warehouses'
    | '/customers/$id'
    | '/invoices/new'
    | '/quotes/new'
    | '/reports/balance-sheet'
    | '/reports/pnl'
    | '/reports/trial-balance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/attendance'
    | '/_authenticated/audit-logs'
    | '/_authenticated/banking'
    | '/_authenticated/bill-payments'
    | '/_authenticated/bills'
    | '/_authenticated/budgets'
    | '/_authenticated/chart-of-accounts'
    | '/_authenticated/compliance'
    | '/_authenticated/credit-notes'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/invoices'
    | '/_authenticated/journal-entries'
    | '/_authenticated/leave'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/payroll'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/quotes'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/setup'
    | '/_authenticated/stock'
    | '/_authenticated/stock-adjustments'
    | '/_authenticated/subscription'
    | '/_authenticated/super-admin'
    | '/_authenticated/suppliers'
    | '/_authenticated/warehouses'
    | '/_authenticated/customers/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/quotes/new'
    | '/_authenticated/reports/balance-sheet'
    | '/_authenticated/reports/pnl'
    | '/_authenticated/reports/trial-balance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-adjustments': {
      id: '/_authenticated/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/stock-adjustments'
      preLoaderRoute: typeof AuthenticatedStockAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal-entries': {
      id: '/_authenticated/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof AuthenticatedJournalEntriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-notes': {
      id: '/_authenticated/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof AuthenticatedCreditNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chart-of-accounts': {
      id: '/_authenticated/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bill-payments': {
      id: '/_authenticated/bill-payments'
      path: '/bill-payments'
      fullPath: '/bill-payments'
      preLoaderRoute: typeof AuthenticatedBillPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banking': {
      id: '/_authenticated/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AuthenticatedBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/trial-balance': {
      id: '/_authenticated/reports/trial-balance'
      path: '/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/pnl': {
      id: '/_authenticated/reports/pnl'
      path: '/pnl'
      fullPath: '/reports/pnl'
      preLoaderRoute: typeof AuthenticatedReportsPnlRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/balance-sheet': {
      id: '/_authenticated/reports/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AuthenticatedReportsBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedQuotesRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedQuotesRouteChildren {
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
}

const AuthenticatedQuotesRouteChildren: AuthenticatedQuotesRouteChildren = {
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
}

const AuthenticatedQuotesRouteWithChildren =
  AuthenticatedQuotesRoute._addFileChildren(AuthenticatedQuotesRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsBalanceSheetRoute: typeof AuthenticatedReportsBalanceSheetRoute
  AuthenticatedReportsPnlRoute: typeof AuthenticatedReportsPnlRoute
  AuthenticatedReportsTrialBalanceRoute: typeof AuthenticatedReportsTrialBalanceRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsBalanceSheetRoute: AuthenticatedReportsBalanceSheetRoute,
  AuthenticatedReportsPnlRoute: AuthenticatedReportsPnlRoute,
  AuthenticatedReportsTrialBalanceRoute: AuthenticatedReportsTrialBalanceRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBankingRoute: typeof AuthenticatedBankingRoute
  AuthenticatedBillPaymentsRoute: typeof AuthenticatedBillPaymentsRoute
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedChartOfAccountsRoute: typeof AuthenticatedChartOfAccountsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedCreditNotesRoute: typeof AuthenticatedCreditNotesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedJournalEntriesRoute: typeof AuthenticatedJournalEntriesRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRouteWithChildren
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedStockAdjustmentsRoute: typeof AuthenticatedStockAdjustmentsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBankingRoute: AuthenticatedBankingRoute,
  AuthenticatedBillPaymentsRoute: AuthenticatedBillPaymentsRoute,
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedChartOfAccountsRoute: AuthenticatedChartOfAccountsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedCreditNotesRoute: AuthenticatedCreditNotesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedJournalEntriesRoute: AuthenticatedJournalEntriesRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRouteWithChildren,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedStockAdjustmentsRoute: AuthenticatedStockAdjustmentsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
