import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpFromLine, Boxes, FileText, RefreshCw, ShoppingCart, Truck, Warehouse, AlertTriangle, Scale } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { fmtMoney } from "@/lib/format";
import { signedQty, MOVEMENT_LABEL } from "@/lib/multi-location";
import { InventoryTransactionExplorer } from "@/components/sifo/InventoryTransactionExplorer";
import { SifoReportTree, type SifoReportTreeItem } from "@/components/sifo/SifoReportTree";
import { SifoPrintTools } from "@/components/sifo/SifoPrintTools";
import { toast } from "sonner";

type Row = { id:string; item_id:string|null; location_id:string|null; movement_type:string; quantity:number; unit_cost:number|null; reference:string|null; transaction_date:string; created_at:string; item_name:string; location_name:string };
const num=(v:any)=>Number(v??0);
const label=(v:string)=>MOVEMENT_LABEL[v]??v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

const REPORTS: SifoReportTreeItem[] = [
 { id:"stock-movement", name:"Stock Movement", description:"Every stock movement and running trail", url:"/inventory-flow-audit", category:"Inventory Control", tags:["movement","stock","audit"] },
 { id:"transfer-register", name:"Transfer Register", description:"Warehouse to store movement", url:"/inventory/transfers", category:"Inventory Control", tags:["warehouse","transfer"] },
 { id:"sales-depletion", name:"Sales Depletion", description:"Cashier sales against store stock", url:"/retail-control-center", category:"Inventory Control", tags:["sales","cashier","pos"] },
 { id:"exception-report", name:"Exception Report", description:"Adjustments, reversals and unusual activity", url:"/stock-adjustments", category:"Inventory Control", tags:["exceptions","adjustments","reversals"] },
 { id:"stock-by-location", name:"Stock by Location", description:"Current balances by warehouse, store and outlet", url:"/inventory/locations", category:"Inventory Control", tags:["location","warehouse","outlet"] },
 { id:"stock-reconciliation", name:"Stock Reconciliation", description:"Review inventory balances and reconciliation", url:"/inventory/reconciliation", category:"Inventory Control", tags:["reconciliation","variance"] },
 { id:"stock-card", name:"Stock Card", description:"Trace item-level quantity and value history", url:"/inventory/stock-card", category:"Inventory Control", tags:["item","history","value"] },
 { id:"stock-takes", name:"Stock Takes", description:"Count, variance, approval and posting", url:"/stock-counts", category:"Inventory Control", tags:["count","variance","approval"] },
];

export function InventoryFlowAudit(){
 const [rows,setRows]=useState<Row[]>([]); const [locations,setLocations]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState(""); const [loc,setLoc]=useState("");
 const load=async()=>{setLoading(true);try{const [m,l]=await Promise.all([supabase.from("stock_movements").select("id,item_id,location_id,movement_type,quantity,unit_cost,reference,transaction_date,created_at,stock_items(name,sku),inventory_locations(name)").order("transaction_date",{ascending:true}).order("created_at",{ascending:true}).limit(2000),supabase.from("inventory_locations").select("id,name,location_type,is_active").order("name")]);if(m.error)throw m.error;if(l.error)throw l.error;setRows((m.data??[]).map((r:any)=>({...r,quantity:num(r.quantity),unit_cost:r.unit_cost==null?null:num(r.unit_cost),item_name:r.stock_items?.name??"Unknown item",location_name:r.inventory_locations?.name??"Unknown location"})));setLocations(l.data??[])}catch(e:any){toast.error(e?.message??"Could not load inventory reports")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const s=q.toLowerCase().trim();return rows.filter(r=>(!loc||r.location_id===loc)&&(!s||`${r.item_name} ${r.reference??""} ${r.movement_type} ${r.location_name}`.toLowerCase().includes(s)))},[rows,q,loc]);
 const stats=useMemo(()=>{const opening=filtered.filter(r=>["opening","production"].includes(r.movement_type)).reduce((s,r)=>s+Math.abs(signedQty(r)),0);const inbound=filtered.filter(r=>["in","purchase","transfer_in","return","adjust_in"].includes(r.movement_type)).reduce((s,r)=>s+Math.abs(signedQty(r)),0);const outbound=filtered.filter(r=>["out","sale","transfer_out","adjust_out"].includes(r.movement_type)).reduce((s,r)=>s+Math.abs(signedQty(r)),0);const value=filtered.reduce((s,r)=>s+Math.abs(r.quantity)*(r.unit_cost??0),0);const exceptions=filtered.filter(r=>["reversal","adjust","adjust_in","adjust_out"].includes(r.movement_type)).length;return{opening,inbound,outbound,value,exceptions}},[filtered]);
 const locationCards=locations.map(l=>{const rs=rows.filter(r=>r.location_id===l.id);return {...l,units:rs.reduce((s,r)=>s+signedQty(r),0),value:rs.reduce((s,r)=>s+signedQty(r)*(r.unit_cost??0),0),moves:rs.length}});
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between print:hidden"><div><h1 className="text-2xl font-bold tracking-tight">Inventory Reports & Control</h1><p className="text-sm text-muted-foreground">Management view of stock flow, locations, sales and exceptions.</p></div><div className="flex gap-2"><SifoPrintTools title="Inventory Reports & Control"/><Button variant="outline" size="sm" onClick={load} disabled={loading}><RefreshCw className={`h-4 w-4 mr-1 ${loading?"animate-spin":""}`}/>Refresh</Button></div></div>
  <div className="hidden print:block border-b-2 border-foreground/20 pb-4"><div className="flex items-start justify-between gap-6"><div><div className="text-xl font-bold">SifoBooks</div><div className="mt-1 text-xs text-muted-foreground">Inventory management report</div></div><div className="text-right"><div className="text-lg font-bold uppercase tracking-wide">Inventory Reports & Control</div><div className="mt-1 text-xs">Generated {new Date().toLocaleString()}</div></div></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><ReportCard icon={Warehouse} title="Opening / Production" value={stats.opening.toLocaleString()} note="Units introduced"/><ReportCard icon={ArrowDownToLine} title="Stock In" value={stats.inbound.toLocaleString()} note="Receipts & transfers"/><ReportCard icon={ArrowUpFromLine} title="Stock Out / Sales" value={stats.outbound.toLocaleString()} note="Issues & sales"/><ReportCard icon={Scale} title="Movement Value" value={fmtMoney(stats.value)} note="Recorded movement cost"/><ReportCard icon={AlertTriangle} title="Exceptions" value={String(stats.exceptions)} note="Adjustments & reversals"/></div>
  <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Activity className="h-4 w-4"/>Operational Flow</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-9 items-center"><Flow icon={Warehouse} text="Opening"/><Arrow/><Flow icon={Boxes} text="Warehouse"/><Arrow/><Flow icon={Truck} text="Transfer"/><Arrow/><Flow icon={Boxes} text="Store / Outlet"/><Arrow/><Flow icon={ShoppingCart} text="Cashier / Sale"/></div></CardContent></Card>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{locationCards.map(l=><Card key={l.id}><CardContent className="p-4"><div className="flex justify-between"><div><div className="font-semibold">{l.name}</div><div className="text-xs text-muted-foreground">{l.location_type}</div></div><Badge variant={l.is_active?"secondary":"outline"}>{l.is_active?"Active":"Inactive"}</Badge></div><div className="grid grid-cols-3 gap-3 mt-4"><Mini title="Units" value={l.units.toLocaleString()}/><Mini title="Value" value={fmtMoney(l.value)}/><Mini title="Movements" value={String(l.moves)}/></div></CardContent></Card>)}</div>
  <Card><CardHeader><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><CardTitle className="text-base">Management Report Filters</CardTitle><p className="text-xs text-muted-foreground">Filter the complete transaction trail before drilling into a transaction.</p></div><div className="flex gap-2 print:hidden"><select value={loc} onChange={e=>setLoc(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All locations</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><Input className="w-56" value={q} onChange={e=>setQ(e.target.value)} placeholder="Item, transfer, sale…"/></div></div></CardHeader></Card>
  <InventoryTransactionExplorer locationId={loc||undefined}/>
  <div className="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)] print:hidden"><SifoReportTree reports={REPORTS} title="Inventory report tree"/><Card><CardHeader><CardTitle className="text-base">Report Centre</CardTitle><p className="text-xs text-muted-foreground mt-1">Clean operational report index for inventory control.</p></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{REPORTS.slice(0,6).map(r=><Link key={r.id} to={r.url as any} className="rounded-xl border p-4 hover:bg-muted/30 hover:border-primary/40 transition-colors"><FileText className="h-5 w-5 text-primary"/><div className="font-semibold mt-2">{r.name}</div><div className="text-xs text-muted-foreground mt-1">{r.description}</div></Link>)}</div></CardContent></Card></div>
  <footer className="hidden print:flex border-t border-foreground/20 pt-3 justify-between text-[10px] text-muted-foreground"><span>Generated by SifoBooks · Inventory Reports & Control</span><span>Page <span className="sifo-page-number" /></span></footer>
  <style>{`@media print { @page { size:A4; margin:14mm 12mm 16mm; } html,body { background:#fff!important; } body { print-color-adjust:exact; -webkit-print-color-adjust:exact; } .sifo-page-number::after { content:counter(page); } table { width:100%!important; border-collapse:collapse!important; } tr { break-inside:avoid; } }`}</style>
 </div>
}
function ReportCard({icon:Icon,title,value,note}:any){return <Card><CardContent className="p-4"><div className="flex gap-2 text-xs text-muted-foreground"><Icon className="h-4 w-4"/>{title}</div><div className="text-xl font-bold mt-2">{value}</div><div className="text-[11px] text-muted-foreground">{note}</div></CardContent></Card>}
function Mini({title,value}:any){return <div><div className="text-[11px] text-muted-foreground">{title}</div><div className="text-sm font-semibold truncate">{value}</div></div>}
function Flow({icon:Icon,text}:any){return <div className="rounded-lg border p-3 flex items-center gap-2"><Icon className="h-4 w-4 text-primary"/><span className="text-sm font-medium">{text}</span></div>}
function Arrow(){return <div className="hidden md:flex justify-center text-muted-foreground">→</div>}
