import { Link } from "@tanstack/react-router";
import { Settings2, Database, ArrowRight, BookOpen, Boxes, ShoppingBag, UtensilsCrossed, Beef, BedDouble, GraduationCap, Banknote, Landmark, Building2, CreditCard, ShoppingCart, ReceiptText, Printer, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { SifoPage } from "@/components/sifo";

type Row={name:string;icon:any;status:"Operational"|"Controlled"|"Configuration";workspace:string;settings:string;data:string;reports:string;posting:string;w:string;s:string;d:string};
const rows:Row[]=[
["Accounting",BookOpen,"Operational","Dashboard, journals, ledger and periods","COA, year, tax, approvals","Accounts, journals, balances","GL, TB, P&L, balance sheet","Double-entry journal","/dashboard","/setup","/chart-of-accounts"],
["Inventory",Boxes,"Operational","Items, locations, receiving, transfers","Warehouses, locations, item master","Items, batches, serials, movements","Valuation, movement, reconciliation","Stock movement / inventory","/inventory","/warehouses","/item-master"],
["Retail POS",ShoppingBag,"Operational","Till, shifts, sales, refunds, cashiers","POS, cashiers, terminals","Sales, payments, shifts","POS sales and integrity","Completed sales → GL","/retail","/pos.settings","/pos-sales"],
["Restaurant",UtensilsCrossed,"Operational","POS, tables, kitchen, menu, orders","Stations, menu, channels","Orders, recipes, tables, payments","Sales, stock, end-of-day","Paid orders → GL","/restaurant","/restaurant/settings","/restaurant/orders"],
["Butchery 2026",Beef,"Operational","Receiving, processing, yield, scale, labels","Cuts, prices, labels, scale","Lots, cuts, yields, stock","Yield, margin, sales","POS + inventory + invoice","/retail/butchery-dashboard","/retail/butchery-products","/retail/butchery-inventory"],
["Hotel",BedDouble,"Controlled","Rooms, reservations, folios, housekeeping","Rooms, rates, channels, controls","Guests, bookings, folios, payments","Occupancy, revenue, night audit","Explicit accounting control","/hotel","/hotel/settings","/hotel/folios"],
["School",GraduationCap,"Controlled","Learners, classes, fees, attendance, boarding","School setup, fees, classes","Students, admissions, marks, attendance","Fees and learner operations","Fee/payment posting control","/school","/school/settings","/school/payments"],
["Payroll & HR",Banknote,"Operational","Employees, runs, statutory, approvals","Payroll setup, rules, grades","Employees, transactions, payslips","Payroll and statutory","Payroll posting engine","/payroll-dashboard","/payroll-setup","/payroll-transactions"],
["Lending",Landmark,"Operational","Borrowers, applications, disbursements, collections","Loan products and controls","Applications, loans, repayments, arrears","Portfolio and collections","Disbursement / repayment RPC","/lending","/lending","/lending/repayments"],
["Property",Building2,"Controlled","Properties, units, tenants, leases, collections","Properties, rent, maintenance","Tenants, leases, charges, payments","Rent roll and statements","Explicit property GL control","/property","/property","/property/collections"],
["Purchasing",ShoppingCart,"Operational","Suppliers, orders, receipts, bills","Supplier, approval, tax controls","Suppliers, POs, receipts, bills","Payables and statements","Bills / receipts / payments","/purchase-orders","/setup","/suppliers"],
["Banking & Cash",CreditCard,"Operational","Accounts, imports, allocation, reconciliation","Bank accounts and rules","Transactions, reconciliations","Bank reconciliation, cashbook","Allocation / journal posting","/banking","/bank-accounts","/banking"],
["ZRA & Compliance",ReceiptText,"Configuration","Smart Invoice, fiscal queue, compliance","TPIN, branch, device, VSDC","Fiscal invoices and queue","VAT, tax, fiscal monitoring","Fiscal boundary after invoice","/zra-smart-invoice","/zra-smart-invoice","/reports/vat"],
["Printing & Devices",Printer,"Configuration","Printers, terminals, print queue","Assignment and routing","Print jobs and device status","Print diagnostics","Receipt / invoice / kitchen","/printing-settings","/printing-settings","/system-health"],
["Administration",ShieldCheck,"Operational","Company, team, roles, approvals, controls","Company setup, roles, permissions","Users, branches, roles, audit","Audit logs and health","Approvals and controlled actions","/admin","/roles","/audit-logs"]
].map(x=>({name:x[0],icon:x[1],status:x[2],workspace:x[3],settings:x[4],data:x[5],reports:x[6],posting:x[7],w:x[8],s:x[9],d:x[10]} as Row));

const tone={Operational:"border-emerald-300 bg-emerald-50 text-emerald-700",Controlled:"border-amber-300 bg-amber-50 text-amber-700",Configuration:"border-sky-300 bg-sky-50 text-sky-700"};

export function ModuleSettingsCentre(){
 const op=rows.filter(x=>x.status==="Operational").length, ctl=rows.filter(x=>x.status==="Controlled").length;
 return <SifoPage>
  <div className="flex flex-wrap items-end justify-between gap-3">
   <div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">SifoBooks 2026</div><h1 className="mt-1 flex items-center gap-2 text-2xl font-bold"><Settings2 className="h-5 w-5 text-primary"/> Module Settings & Administration</h1><p className="mt-1 max-w-4xl text-sm text-muted-foreground">Central control for workspaces, settings, data tables, reports and posting boundaries.</p></div>
   <div className="flex gap-2"><Link to="/admin" className="rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-muted">Administration</Link><Link to="/module-audit" className="rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-muted">Audit</Link><Link to="/system-health" className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">Health</Link></div>
  </div>
  <div className="grid grid-cols-2 gap-2 md:grid-cols-4"><Card className="p-3"><div className="text-xs text-muted-foreground">Modules mapped</div><div className="mt-1 text-xl font-bold">{rows.length}</div></Card><Card className="p-3"><div className="text-xs text-muted-foreground">Operational</div><div className="mt-1 text-xl font-bold text-emerald-700">{op}</div></Card><Card className="p-3"><div className="text-xs text-muted-foreground">Controlled</div><div className="mt-1 text-xl font-bold text-amber-700">{ctl}</div></Card><Card className="p-3"><div className="text-xs text-muted-foreground">Configuration</div><div className="mt-1 text-xl font-bold text-sky-700">{rows.length-op-ctl}</div></Card></div>
  <Card className="overflow-hidden rounded-xl"><div className="border-b bg-muted/20 px-4 py-3"><div className="flex items-center gap-2 font-semibold"><Database className="h-4 w-4 text-primary"/> Module data map</div><p className="mt-0.5 text-xs text-muted-foreground">Dense 2026 tabulation. Use the three action icons to open the workspace, settings or data screen.</p></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-sm"><thead className="bg-muted/40 text-[11px] uppercase tracking-wide text-muted-foreground"><tr>{["Module","Status","Workspace","Settings","Data / tables","Reports","Posting","Open"].map(h=><th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const I=r.icon;return <tr key={r.name} className="border-t align-top hover:bg-muted/20"><td className="px-3 py-3 font-semibold"><div className="flex min-w-[145px] items-center gap-2"><I className="h-4 w-4 shrink-0 text-primary"/>{r.name}</div></td><td className="px-3 py-3"><Badge variant="outline" className={tone[r.status]}>{r.status}</Badge></td><td className="max-w-[190px] px-3 py-3 text-xs text-muted-foreground">{r.workspace}</td><td className="max-w-[190px] px-3 py-3 text-xs text-muted-foreground">{r.settings}</td><td className="max-w-[190px] px-3 py-3 text-xs text-muted-foreground">{r.data}</td><td className="max-w-[190px] px-3 py-3 text-xs text-muted-foreground">{r.reports}</td><td className="max-w-[190px] px-3 py-3 text-xs text-muted-foreground">{r.posting}</td><td className="px-3 py-3"><div className="flex justify-end gap-1.5"><Link title="Workspace" to={r.w as never} className="rounded-md border p-1.5 hover:bg-muted"><ArrowRight className="h-3.5 w-3.5"/></Link><Link title="Settings" to={r.s as never} className="rounded-md border p-1.5 hover:bg-muted"><Settings2 className="h-3.5 w-3.5"/></Link><Link title="Data" to={r.d as never} className="rounded-md border p-1.5 hover:bg-muted"><Database className="h-3.5 w-3.5"/></Link></div></td></tr>})}</tbody></table></div>
  </Card>
 </SifoPage>;
}
