import { Printer, FileDown } from "lucide-react";
import { Button } from "@/components/ui/button";

export function SifoPrintTools({ title = "Print document", className = "" }: { title?: string; className?: string }) {
  const print = () => window.print();
  return (
    <div className={`sifo-print-tools flex flex-wrap gap-2 ${className}`}>
      <Button type="button" variant="outline" size="sm" onClick={print}>
        <Printer className="mr-2 h-4 w-4" /> Print / Preview
      </Button>
      <Button type="button" variant="ghost" size="sm" onClick={print} title={title}>
        <FileDown className="mr-2 h-4 w-4" /> PDF / Save as PDF
      </Button>
    </div>
  );
}

export function SifoPrintDocument({
  companyName,
  companyDetails,
  documentTitle,
  documentNumber,
  children,
  footer,
}: {
  companyName?: string;
  companyDetails?: React.ReactNode;
  documentTitle: string;
  documentNumber?: string | null;
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  return (
    <div className="sifo-print-document mx-auto w-full max-w-5xl bg-background text-foreground">
      <header className="sifo-print-header hidden border-b-2 border-foreground/20 pb-4 print:block">
        <div className="flex items-start justify-between gap-6">
          <div>
            <div className="text-xl font-bold tracking-tight">{companyName || "SifoBooks"}</div>
            <div className="mt-1 text-xs text-muted-foreground">{companyDetails}</div>
          </div>
          <div className="text-right">
            <div className="text-lg font-bold uppercase tracking-wide">{documentTitle}</div>
            {documentNumber && <div className="mt-1 font-mono text-xs">{documentNumber}</div>}
          </div>
        </div>
      </header>
      {children}
      <footer className="sifo-print-footer hidden border-t border-foreground/20 pt-3 print:block">
        <div className="flex justify-between gap-4 text-[10px] text-muted-foreground">
          <span>{footer || "Generated by SifoBooks"}</span>
          <span>Page <span className="sifo-page-number" /></span>
        </div>
      </footer>
    </div>
  );
}

export function SifoPrintStyles() {
  return (
    <style>{`
      @media print {
        @page { size: A4; margin: 14mm 12mm 16mm; }
        html, body { background: white !important; }
        body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
        .sifo-print-tools, button, [role="button"] { display: none !important; }
        .sifo-print-document { max-width: none !important; width: 100% !important; box-shadow: none !important; }
        .sifo-print-document * { box-shadow: none !important; }
        .sifo-print-header, .sifo-print-footer { display: block !important; }
        table { width: 100% !important; border-collapse: collapse !important; }
        thead { display: table-header-group; }
        tr { break-inside: avoid; }
        .print-break-before { break-before: page; }
        .print-no-break { break-inside: avoid; }
        .sifo-page-number::after { content: counter(page); }
      }
    `}</style>
  );
}
