import type { ReactNode } from "react";
import { Download, FileSpreadsheet, FileText, Mail, Printer, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

export type SifoReportColumn = {
  key: string;
  label: string;
  align?: "left" | "center" | "right";
};

export type SifoReportViewerProps = {
  title: string;
  subtitle?: string;
  period?: string;
  filters?: ReactNode;
  columns: SifoReportColumn[];
  rows: Array<Record<string, ReactNode>>;
  totals?: Array<{ label: string; value: ReactNode; emphasis?: boolean }>;
  onGenerate?: () => void;
  onPrint?: () => void;
  onPdf?: () => void;
  onExcel?: () => void;
  onCsv?: () => void;
  onEmail?: () => void;
  onRowClick?: (row: Record<string, ReactNode>) => void;
  loading?: boolean;
};

export function SifoReportViewer({
  title,
  subtitle,
  period,
  filters,
  columns,
  rows,
  totals = [],
  onGenerate,
  onPrint,
  onPdf,
  onExcel,
  onCsv,
  onEmail,
  onRowClick,
  loading = false,
}: SifoReportViewerProps) {
  return (
    <section className="sifo-report-page">
      <header className="sifo-page-header print:hidden">
        <div className="min-w-0">
          <div className="sifo-breadcrumb">Reports / {title}</div>
          <h1>{title}</h1>
          {subtitle && <p>{subtitle}</p>}
        </div>
        <div className="sifo-page-actions">
          {onGenerate && <Button variant="outline" className="h-9" onClick={onGenerate}><RefreshCw className="mr-1.5 h-4 w-4" />Generate Report</Button>}
          {onPrint && <Button variant="outline" className="h-9" onClick={onPrint}><Printer className="mr-1.5 h-4 w-4" />Print</Button>}
        </div>
      </header>

      {filters && <div className="sifo-report-filters print:hidden">{filters}</div>}

      <article className="sifo-report-paper">
        <div className="sifo-report-heading">
          <div>
            <div className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">SifoBooks</div>
            <h2>{title}</h2>
            {subtitle && <p>{subtitle}</p>}
          </div>
          {period && <div className="sifo-report-period">{period}</div>}
        </div>

        <div className="overflow-x-auto">
          <table className="sifo-report-table">
            <thead><tr>{columns.map(c => <th key={c.key} className={c.align === "right" ? "text-right" : c.align === "center" ? "text-center" : "text-left"}>{c.label}</th>)}</tr></thead>
            <tbody>
              {loading ? <tr><td colSpan={columns.length} className="sifo-table-state">Generating report…</td></tr> : rows.length === 0 ? <tr><td colSpan={columns.length} className="sifo-table-state">No data for the selected criteria.</td></tr> : rows.map((row, index) => <tr key={index} onClick={() => onRowClick?.(row)} className={onRowClick ? "cursor-pointer hover:bg-muted/50" : undefined}>{columns.map(c => <td key={c.key} className={c.align === "right" ? "text-right tabular-nums" : c.align === "center" ? "text-center" : undefined}>{row[c.key] ?? "—"}</td>)}</tr>)}
            </tbody>
          </table>
        </div>

        {totals.length > 0 && <div className="sifo-report-totals">
          {totals.map(t => <div key={t.label} className={t.emphasis ? "sifo-report-total emphasis" : "sifo-report-total"}><span>{t.label}</span><strong>{t.value}</strong></div>)}
        </div>}

        <footer className="sifo-report-footer print:hidden">
          <span>Generated by SifoBooks</span>
          <div className="flex flex-wrap gap-1">
            {onPdf && <Button variant="ghost" size="sm" onClick={onPdf}><FileText className="mr-1 h-3.5 w-3.5" />PDF</Button>}
            {onExcel && <Button variant="ghost" size="sm" onClick={onExcel}><FileSpreadsheet className="mr-1 h-3.5 w-3.5" />Excel</Button>}
            {onCsv && <Button variant="ghost" size="sm" onClick={onCsv}><Download className="mr-1 h-3.5 w-3.5" />CSV</Button>}
            {onEmail && <Button variant="ghost" size="sm" onClick={onEmail}><Mail className="mr-1 h-3.5 w-3.5" />Email</Button>}
          </div>
        </footer>
      </article>
    </section>
  );
}
